# Generated by Django 5.2.7 on 2025-11-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'unique_together': {('title', 'director', 'year')},
            },
        ),
    ]
